spring.datasource.url=jdbc:mysql://nozomi.proxy.rlwy.net:18456/railway
spring.datasource.username=root
spring.datasource.password=ZujdufmDNSThfvtfZNdDbOnJtBRXoaRb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true